CREATE TABLE `KEYS` (
    KEY_SID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DOOR_SID INT NOT NULL,
    IS_EXISTS BOOLEAN NOT NULL DEFAULT 1,

    FOREIGN KEY (DOOR_SID) REFERENCES `DOORS` (DOOR_SID)
);
